services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3200:8080
    depends_on:
      - database

  database:
    image: postgres:16-alpine3.19
    ports:
      - 5555:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jeanpormanove
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret

volumes:
  psql-data:
