version: '3'
services:
  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - db
    environment:
      - PORT=3333
      - HOST=localhost
      - LOG_LEVEL=info
      - APP_KEY=UIftWVg2Slweu1eRN2VvObGvbZ-5KUdw
      - NODE_ENV=development
      - SESSION_DRIVER=cookie
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=admin
